name: .NET Debug Build and Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    env:
      Solution_Name: Xcaciv.Loader.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name
    - name: Debug Build
      run: dotnet build $env:Solution_Name --no-restore --configuration Debug
    - name: Test with dotnet
      run: dotnet test $env:Solution_Name --no-build --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: TestResults-${{ matrix.dotnet-version }}
      if: ${{ always() }}